### ISSUE TITLE
sharing button?

### ISSUE THREAD

**Issue by MrT666** [bosorioo/wordle-unlimited#1]
Why there is no Sharing button  like the other versions?!

**Comment by bosorioo** [comment]
I feel like it's pointless to share the result of a word you guessed when it's not synchronized to everyone else's word for the day.  
Also, you can play this version multiple times a day, so the share seemed insignificant.
I might implement it eventually though

**Comment by bosorioo** [comment]
Implemented a share button in commit https://github.com/bosorioo/wordle-unlimited/commit/5c736b1a8f63ad9a553159c456dbac89392999b2
