### ISSUE TITLE
Terms of use

### ISSUE THREAD

**Issue by avivkeller** [bosorioo/wordle-unlimited#2]
Hey there @bosorioo,

I am creating a project, and I would like to use your code within it. There is no license on your repository, and so I do not your terms of use. I will provide credit, and any licensing you want me to apply. 

If you could please let me know if/how I can use your great work, I would be very grateful.

From,
RedYetiDev

**Comment by bosorioo** [comment]
Feel free to do so!
You can use and modify it however you like, no credits needed. It makes me glad to be useful to others.

**Comment by avivkeller** [comment]
Thank you so much! I will provide credit anyway.
